with open('C:/xampp/htdocs/SPAC/dashboards/barangay/index.php', 'rb') as f:
    content = f.read()

old_menu = b'sidebar-menu">\r\n        <div class="menu-section">OVERVIEW</div>\r\n        <a class="menu-item" href="index.php"><span class="menu-dot"></span> Dashboard</a>\r\n        <a class="menu-item" href="index.php?section=profile"><span class="menu-dot"></span> Barangay Profile <span class="menu-section-inline">PEOPLE</span></a>\r\n        <a class="menu-item" href="index.php?section=officials"><span class="menu-dot"></span> Officials &amp; Staff <span class="menu-badge"><?= $total_officials ?></span></a>\r\n        <a class="menu-item" href="index.php?section=zones"><span class="menu-dot"></span> <?= htmlspecialchars($area_label) ?> Leaders <span class="menu-badge"><?= $total_zones ?></span></a>\r\n        <a class="menu-item" href="index.php?section=households"><span class="menu-dot"></span> Households <span class="menu-badge"><?= number_format($total_families) ?></span></a>\r\n        <a class="menu-item" href="index.php?section=residents"><span class="menu-dot"></span> Residents <span class="menu-badge"><?= number_format($total_residents) ?></span></a>\r\n        <div class="menu-section">REPORTS</div>\r\n        <a class="menu-item" href="statistics.php"><span class="menu-dot"></span> Statistics <span class="menu-section-inline">SERVICES</span></a>\r\n        <a class="menu-item" href="manage_areas.php"><span class="menu-dot"></span> Manage Areas</a>\r\n        <a class="menu-item" href="import_residents.php"><span class="menu-dot"></span> Import Residents</a>\r\n        <a class="menu-item" href="index.php?section=ayuda"><span class="menu-dot"></span> Ayuda / Assistance</a>\r\n        <a class="menu-item" href="index.php?section=qr"><span class="menu-dot"></span> Scan QR / History <span class="menu-section-inline">MANAGEMENT</span></a>\r\n        <a class="menu-item" href="index.php?section=alerts">\r\n            <span class="menu-dot"></span> Alerts\r\n            <?php if ($active_alerts > 0): ?>\r\n            <span class="menu-badge alert"><?= $active_alerts ?></span>\r\n            <?php endif;'

new_menu = b'sidebar-menu">\r\n        <div class="menu-section">Overview</div>\r\n        <button class="menu-item" onclick="showSection(\'dashboard\', this)"><span class="menu-dot"></span> Dashboard</button>\r\n        <button class="menu-item" onclick="showSection(\'profile\', this)"><span class="menu-dot"></span> Barangay Profile</button>\r\n        <div class="menu-section">People</div>\r\n        <button class="menu-item" onclick="showSection(\'officials\', this)"><span class="menu-dot"></span> Officials &amp; Staff <span class="menu-badge"><?= $total_officials ?></span></button>\r\n        <button class="menu-item" onclick="showSection(\'zones\', this)"><span class="menu-dot"></span> <?= htmlspecialchars($area_label) ?> Leaders <span class="menu-badge"><?= $total_zones ?></span></button>\r\n        <button class="menu-item" onclick="showSection(\'households\', this)"><span class="menu-dot"></span> Households <span class="menu-badge"><?= number_format($total_families) ?></span></button>\r\n        <button class="menu-item" onclick="showSection(\'residents\', this)"><span class="menu-dot"></span> Residents <span class="menu-badge"><?= number_format($total_residents) ?></span></button>\r\n        <div class="menu-section">Reports</div>\r\n        <button class="menu-item" onclick="window.location.href=\'statistics.php\'"><span class="menu-dot"></span> Statistics</button>\r\n        <div class="menu-section">Services</div>\r\n        <button class="menu-item" onclick="window.location.href=\'manage_areas.php\'"><span class="menu-dot"></span> Manage Areas</button>\r\n        <button class="menu-item" onclick="window.location.href=\'import_residents.php\'"><span class="menu-dot"></span> Import Residents</button>\r\n        <button class="menu-item" onclick="showSection(\'ayuda\', this)"><span class="menu-dot"></span> Ayuda / Assistance</button>\r\n        <button class="menu-item" onclick="showSection(\'qr\', this)"><span class="menu-dot"></span> Scan QR / History</button>\r\n        <div class="menu-section">Management</div>\r\n        <button class="menu-item" onclick="showSection(\'alerts\', this)">\r\n            <span class="menu-dot"></span> Alerts\r\n            <?php if ($active_alerts > 0): ?>\r\n            <span class="menu-badge alert"><?= $active_alerts ?></span>\r\n            <?php endif;'

content = content.replace(old_menu, new_menu)

with open('C:/xampp/htdocs/SPAC/dashboards/barangay/index.php', 'wb') as f:
    f.write(content)

print("Fix:", "OK" if b"showSection('dashboard'" in content else "FAILED")
